name: refrescante-run-tests

on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development
jobs:
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            # Check out the code
            - uses: actions/checkout@v3

            # Setup bun
            - name: Setup bun
              uses: oven-sh/bun-action@v2
              with:
                bun-version: latest

            # Install dependencies
            - name: Install dependencies
              run: bun install

            # Run tests
            - name: Run tests
              run: bun test